bot-account: 123  # QQ bot account
bot-password: 'No_BUG_Report'  # QQ bot password
bot-login-device: 'ANDROID_PHONE'  # ANDROID_PHONE, ANDROID_PAD, ANDROID_WATCH, IPAD, MACOS

super-admin-account: [123, 456]  # super administrator accounts

player-group: 10000  # the number of QQ group where players are in
inner-player-group: 10010  # not very useful, just ignore it
op-group: 10086  # the group where managers and operators in
check-in-group: 10101  # the group to check in

use-mysql: false  # use MySQL or SQLite
mysql-host:
mysql-port:
mysql-database:
mysql-username:
mysql-password:

QWeather-APIKey: 'qwq'  # 和风天气API密钥

message-forward:
  group-to-server: true
  server-to-group: true

bot-speak-possibility: 5  # percent  # bot may seldom speak something written at "messages.yml" - "bot-greetings", set this number to decide the possibility, set to 0 to disable

message-head-format: '&f<&b{SENDER}&f> '

command-prefix: '#'

bind-id-and-qq:
  # this function MUST be enabled
  online-mode: true
  whitelist: true  # recommend enabling this in order for a better experience
  modify-namecard: true

tps-check:
  enable: true
  cron: '0 0/1 * * * ?'  # to decide the frequency of TPS-Check
  threshold: 17.0  # ticks  # when server TPS is lower than this number, send a warning message to the op-group above

online-player-record:
  enable: false
  cron: '0 0/10 * * * ?'

message-length-limit:
  enable: true
  ignore-ops: true
  maximum-length: 60  # chars

# Stp is needed
stop-server:
  teleport-players:
    enabled: true
    target-server: 'catland-shelter'

daily-greetings:
  morning:
    enable: true
    cron: '0 0 7 * * ?'
    city: '苏州'
  night:
    enable: true
    cron: '0 0 23 * * ?'

# bot may repeat the message that has been repeated several times
bot-repeater:
  enabled: true
  # NEVER set this to 1 unless you simply want a repeater
  frequency: 3  # counts  # set this number to decide the frequency

block-words:
  enabled: true
  warning-message: '你的消息含有屏蔽词，已撤回'  # set this an empty string ('') to disable sending warning message
  blocklist:
    - '（脏话）'
    - '（敏感词）'

# 除非你已接入猫猫大陆审核专用系统 COPA，否则请禁用此项
player-group-auto-manage:
  enable: false
  reject-message: '请加群 705754458 以获取入群验证码'

check-in-group-auto-manage:
  enable: true
  minimum-QQ-level: 10  # 最低QQ等级，防小号。设置为 0 则关闭检测

# 测试功能
netease-cloud-music:
  profile:
    phone: '10000000000'
    password: 'qwerty123456'

# 弃用功能
inner-player-group-auto-manage:
  invite:
    enable: true
    cron: '0 0 0/1 * * ?'
    requirement: 1000  # minutes per week
    blacklist:
      - 'qwq'
      - 'qaq'
  kick:
    enable: true
    cron: '0 0 18 ? * 7'
    requirement: 1000
    whitelist:
      - 'Maplef_snow'
      - 'xinQi5'

